export interface ChatProps {
    id: number;
    avatar: string;
    name: string;
    lastMessage: string;
    lastMessageTime: string;
    createdAt: Date;
    createdBy: Date;
    label?: 'string';
    type: 'private' | 'group' | 'channel';
    // If private
    username?: string; // Made optional since groups don't need these
    phone?: string; // Made optional since groups don't need these
    email?: string; // Made optional since groups don't need these
    bio?: string; // Made optional since groups don't need these
    birthday?: string; // Made optional since groups don't need these

    // if Group or Channel
    members?: string[];
    admins?: string[]; // Required (groups/channels must have admins)
    description?: string;
  }

  export const ChatsData: ChatProps[] = [
    {
      id: 1,
      name: 'Alice',
      avatar: '',
      lastMessage: 'Hey there!',
      lastMessageTime: '10:45 AM',
      type: 'private',
      phone: '+1234567890',
      email: 'alice@example.com',
      bio: 'Frontend developer who loves React',
      birthday: '15/05/1992',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 2,
      name: 'Bob',
      avatar: '',
      lastMessage: 'See you later',
      lastMessageTime: '9:20 AM',
      type: 'private',
      phone: '+1987654321',
      email: 'bob@example.com',
      bio: 'Project manager at TechCorp',
      birthday: '22/11/1985',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 3,
      name: 'Charlie',
      avatar: '',
      lastMessage: 'Let’s meet up tomorrow.',
      lastMessageTime: '8:15 AM',
      type: 'private',
      phone: '+1122334455',
      email: 'charlie@example.com',
      bio: 'Computer science student',
      birthday: '03/09/2000',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 4,
      name: 'Diana',
      avatar: '',
      lastMessage: 'Got it, thanks!',
      lastMessageTime: '7:05 AM',
      type: 'private',
      phone: '+1567890123',
      email: 'diana@example.com',
      bio: 'UX Designer',
      birthday: '18/07/1993',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 5,
      name: 'Eve',
      avatar: '',
      lastMessage: 'Did you finish the project?',
      lastMessageTime: 'Yesterday',
      type: 'private',
      phone: '+1345678901',
      email: 'eve@example.com',
      bio: 'Senior Developer',
      birthday: '29/02/1988',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 6,
      name: 'Frank',
      avatar: '',
      lastMessage: 'Let’s grab coffee later.',
      lastMessageTime: 'Yesterday',
      type: 'private',
      phone: '+1478523690',
      email: 'frank@example.com',
      bio: 'Data Analyst who enjoys Python',
      birthday: '12/04/1991',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 7,
      name: 'Grace',
      avatar: '',
      lastMessage: 'All tasks are completed.',
      lastMessageTime: 'Monday',
      type: 'private',
      phone: '+1987456321',
      email: 'grace@example.com',
      bio: 'DevOps engineer at CloudNet',
      birthday: '25/12/1987',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 8,
      name: 'Henry',
      avatar: '',
      lastMessage: 'Wanna study together?',
      lastMessageTime: 'Sunday',
      type: 'private',
      phone: '+1765432198',
      email: 'henry@example.com',
      bio: 'AI/ML Enthusiast',
      birthday: '09/06/1999',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 9,
      name: 'Isla',
      avatar: '',
      lastMessage: 'Happy birthday!',
      lastMessageTime: 'Sunday',
      type: 'private',
      phone: '+1654321987',
      email: 'isla@example.com',
      bio: 'Digital Artist',
      birthday: '30/08/1994',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 10,
      name: 'Jack',
      avatar: '',
      lastMessage: 'I’ll check the docs.',
      lastMessageTime: 'Saturday',
      type: 'private',
      phone: '+1231231234',
      email: 'jack@example.com',
      bio: 'Backend Developer',
      birthday: '14/03/1989',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 11,
      name: 'Kara',
      avatar: '',
      lastMessage: 'Notes shared!',
      lastMessageTime: 'Saturday',
      type: 'private',
      phone: '+1333555777',
      email: 'kara@example.com',
      bio: 'Biology major at university',
      birthday: '07/11/2001',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 12,
      name: 'Leo',
      avatar: '',
      lastMessage: 'Let’s catch up soon.',
      lastMessageTime: 'Friday',
      type: 'private',
      phone: '+1223344556',
      email: 'leo@example.com',
      bio: 'Freelance Videographer',
      birthday: '21/01/1995',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 13,
      name: 'Mia',
      avatar: '',
      lastMessage: 'Sent the brief.',
      lastMessageTime: 'Thursday',
      type: 'private',
      phone: '+1777888999',
      email: 'mia@example.com',
      bio: 'Product Manager',
      birthday: '05/10/1990',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 14,
      name: 'Nate',
      avatar: '',
      lastMessage: 'Can we revise that?',
      lastMessageTime: 'Wednesday',
      type: 'private',
      phone: '+1666777888',
      email: 'nate@example.com',
      bio: 'Quality Assurance Engineer',
      birthday: '17/07/1986',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 15,
      name: 'Olivia',
      avatar: '',
      lastMessage: 'Working on it.',
      lastMessageTime: 'Tuesday',
      type: 'private',
      phone: '+1444555666',
      email: 'olivia@example.com',
      bio: 'Math PhD candidate',
      birthday: '28/02/1998',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 16,
      name: 'Paul',
      avatar: '',
      lastMessage: 'I’ll call you back.',
      lastMessageTime: 'Today',
      type: 'private',
      phone: '+1555666777',
      email: 'paul@example.com',
      bio: 'Travel Blogger',
      birthday: '13/09/1992',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 17,
      name: 'Queenie',
      avatar: '',
      lastMessage: 'Meeting is at 4 PM.',
      lastMessageTime: 'Today',
      type: 'private',
      phone: '+1444333222',
      email: 'queenie@example.com',
      bio: 'Finance Lead',
      birthday: '24/04/1984',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 18,
      name: 'Ryan',
      avatar: '',
      lastMessage: 'Need help with the code.',
      lastMessageTime: 'Today',
      type: 'private',
      phone: '+1777222111',
      email: 'ryan@example.com',
      bio: 'Coding bootcamp student',
      birthday: '06/12/2002',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 19,
      name: 'Sophie',
      avatar: '',
      lastMessage: 'Haha that was funny!',
      lastMessageTime: 'Today',
      type: 'private',
      phone: '+1333444555',
      email: 'sophie@example.com',
      bio: 'Comedy writer',
      birthday: '19/05/1996',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 20,
      name: 'Tom',
      avatar: '',
      lastMessage: 'Done with review.',
      lastMessageTime: 'Today',
      type: 'private',
      phone: '+1222111444',
      email: 'tom@example.com',
      bio: 'Tech lead at SoftBase',
      birthday: '31/10/1983',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 21,
      name: 'React Enthusiasts',
      avatar: '',
      lastMessage: 'Alice: Check out this new hook!',
      lastMessageTime: '11:30 AM',
      type: 'group',
      members: ['Alice', 'Eve', 'Jack', 'Ryan'],
      admins: ['Alice'],
      description: 'A place to discuss all things React',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 22,
      name: 'Work Team',
      avatar: '',
      lastMessage: 'Tom: Meeting at 3pm in Conference Room B',
      lastMessageTime: '10:15 AM',
      type: 'group',
      members: ['Bob', 'Eve', 'Grace', 'Mia', 'Tom'],
      admins: ['Tom'],
      description: 'Daily work updates and coordination',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 23,
      name: 'Weekend Warriors',
      avatar: '',
      lastMessage: 'Frank: Whos up for hiking this Saturday?',
      lastMessageTime: 'Yesterday',
      type: 'group',
      members: ['Alice', 'Diana', 'Frank', 'Isla', 'Sophie'],
      admins: ['Frank'],
      description: 'Plan fun weekend outings',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 24,
      name: 'Study Group CS101',
      avatar: '',
      lastMessage: 'Henry: I shared the notes in the drive',
      lastMessageTime: 'Monday',
      type: 'group',
      members: ['Charlie', 'Henry', 'Kara', 'Olivia', 'Ryan'],
      admins: ['Henry'],
      description: 'Collaborative learning for CS101 course',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 25,
      name: 'Project Alpha',
      avatar: '',
      lastMessage: 'Grace: Deployment completed successfully',
      lastMessageTime: 'Sunday',
      type: 'group',
      members: ['Bob', 'Grace', 'Jack', 'Nate', 'Queenie'],
      admins: ['Grace'],
      description: 'Internal team for Alpha project development',
      createdAt: new Date(),
      createdBy: new Date(),
    },
    {
      id: 26,
      name: 'Dev Channel',
      avatar: '',
      lastMessage: 'New deployment is live!',
      lastMessageTime: 'Today',
      type: 'channel',
      createdAt: new Date(),
      createdBy: new Date(),
      admins: ['Grace'],
      members: ['Grace', 'Mia', 'Tom', 'Nate'],
      description: 'Updates and news related to development.',
    },
    {
      id: 27,
      name: 'Marketing Hub',
      avatar: '',
      lastMessage: 'Campaign launch scheduled for next week.',
      lastMessageTime: 'Yesterday',
      type: 'channel',
      createdAt: new Date(),
      createdBy: new Date(),
      admins: ['Queenie'],
      members: ['Queenie', 'Eve', 'Sophie'],
      description: 'Central place for marketing updates and collaboration.',
    }
  ];
  