export enum AttachmentType {
  IMAGE = "image",
  VIDEO = "video",
  AUDIO = "audio",
  VOICE = "voice",
  LOCATION = "location",
  FILE = "file",
  PDF = "pdf",
  WORD = "word",
  EXCEL = "excel",
  PPT = "powerpoint",
  ARCHIVE = "archive",
  TEXT = "text",
  CODE = "code",
}
