export enum ModalType {
  MEDIA = "media",
  FRIEND_REQUEST = "friend-request",
  MESSAGE = "message",
  FORWARD_MESSAGE = "forward-message",
  DELETE_MESSAGE = "delete-message",
  DELETE_FOLDER = "delete-folder",
  DELETE_CHAT = "delete-chat",
  DELETE_DIRECT_CHAT = "delete-direct-chat",
  ADD_FOLDER = "add-folder",
  ADD_CONTACT = "add-contact",
  MUTE = "mute",
  BLOCK_USER = "block-user",
  UNBLOCK_USER = "unblock-user",
  UNFRIEND = "unfriend",
  ADD_MEMBER = "add-member",
  SET_NICKNAME = "set-nickname",
  LEAVE_CHAT = "leave-chat",
  CALL = "call",
}

export enum CallStatus {
  CONNECTING = "connecting",
  CONNECTED = "connected",
  INCOMING = "incoming",
  OUTGOING = "outgoing",
  CANCELED = "canceled",
  REJECTED = "rejected",
  ENDED = "ended",
  ERROR = "error",
}
