export enum ModalType {
  OVERLAY = "overlay",
  MEDIA = "media",
  FRIEND_REQUEST = "friend-request",
  FORWARD_MESSAGE = "forward-message",
  DELETE_MESSAGE = "delete-message",
  DELETE_FOLDER = "delete-folder",
  DELETE_CHAT = "delete-chat",
  FOLDER = "folder",
  MUTE = "mute",
  BLOCK_USER = "block-user",
  UNBLOCK_USER = "unblock-user",
  UNFRIEND = "unfriend",
  ADD_MEMBER = "add-member",
  SET_NICKNAME = "set-nickname",
  LEAVE_CHAT = "leave-chat",
  CALL = "call",
  DELETE_CALL = "DELETE_CALL",
}
